name: bpftrace
version: 'v0.9.3'
summary: high-level tracing language for Linux eBPF
description: 'BPFtrace is a high-level tracing language for Linux enhanced Berkeley Packet Filter available in recent Linux kernels. BPFtrace uses LLVM as a backend to compile scripts to BPF-bytecode and makes use of BCC for interacting with the Linux BPF system, as well as existing Linux tracing capabilities: kernel dynamic tracing, user-level dynamic tracing and tracepoints.'

confinement: strict
grade: stable
architectures: [amd64]
base: core18

parts:
    kernel-tools-edge:
        source: .
        plugin: make
        override-build: |
            add-apt-repository ppa:canonical-kernel-team/kernel-tools-edge
            apt-get update
        build-packages:
            - software-properties-common

    bpftrace:
        after:
            - kernel-tools-edge
        source: .
        plugin: make
        override-build: |
            true
        stage-packages:
            - bpftrace

apps:
    bpftrace:
        command: bpftrace
        plugs: [ home, system-trace ]
        environment:
            LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/x86-64-linux-gnu:$SNAP/usr/lib/x86-64-linux-gnu:$SNAP/usr/lib/gcc/x86_64-linux-gnu/6

